"""Tell some fun facts"""
import random
import time
import os
import snowboydecoder
from flite import flite

FACTS = [
    "A 2007 Gallup poll revealed that both men and women were equally likely to own a cat.",
    "Abraham Lincoln kept four cats in the White House.",
    "Abraham Lincoln lived with 4 cats in the White House.",
    "A cat almost never meows at another cat, mostly just humans. Cats typically will spit, purr, and hiss at other cats.",
    "A cat can jump up to five times its own height in a single bound.",
    "A cat can jump up to six times its length.",
    "A cat can’t climb head first down a tree because every claw on a cat’s paw points the same way. To get down from a tree, a cat must back down.",
    "A cat can travel at a top speed of approximately 31 miles per hour over a short distance.",
    "A cat has 230 bones in its body. A human has 206. A cat has no collarbone, so it can fit through any opening the size of its head.",
    "A cat has been mayor of Talkeetna, Alaska, for 15 years. His name is Stubbs.",
    "A cat has detected his human`s breast cancer.",
    "A cat has five toes on his front paws, and four on the back, unless he`s a polydactyl.",
    "A cat purrs at a frequency of 25 to 150 Hertz.",
    "A cat rubs against people to mark its territory.",
    "A cats average life expectancy increased by a whole year between 2002 and 2012.",
    "A cat’s back is extremely flexible because it has up to 53 loosely fitting vertebrae. Humans only have 34.",
    "A cat`s brain is 90% similar to a human`s — more similar than to a dog`s.",
    "A cat`s carbon footprint is similar to that of a VW Bug, whereas a dog`s is more like a Hummer.",
    "A cat’s hearing is better than a dog’s. A cat can hear high-frequency sounds up to two octaves higher than a human.",
    "A cat’s heart beats nearly twice as fast as a human heart, at 110 to 140 beats a minute.",
    "A cat’s jaw can’t move sideways, so a cat can’t chew large chunks of food.",
    "A cat`s nose is ridged with a unique pattern, just like a human fingerprint.",
    "A cat’s nose pad is ridged with a unique pattern, just like the fingerprint of a human. ",
    "A cat`s purr may be a form of self-healing, as it can be a sign of nervousness as well as contentment.",
    "A cat usually has about 12 whiskers on each side of its face.",
    "A cat will refuse food it doesnt like to the point of starvation.",
    "Adult cats only meow to communicate with humans.",
    "A female cat is called a queen or a molly.",
    "A group of cats is called a clowder.",
    "A group of kittens is known as a kindle.",
    "A house cat is faster than Usain Bolt.",
    "A lot of cats are actually lactose intolerant.",
    "And one ran for mayor of Mexico City in 2013.",
    "Approximately 1/3 of cat owners think their pets are able to read their minds. ",
    "As strange as it sounds, a green cat was actually once born in Denmark.",
    "A trained cat could easily beat Usain Bolt in the 200-meter dash.",
    "Basically all cartoon cats lied to us: Raw fish is off the table for cats as well.",
    "Basically, cats have a lower social IQ than dogs but can solve more difficult cognitive problems when they feel like it.",
    "Bill Clintons cat, Socks, was said to receive more letters than the President himself.",
    "Black cats are bad luck in the United States, but they are good luck in the United Kingdom and Australia.",
    "Cat breeders are called catteries.",
    "Catnip produces an effect on your cat that is similar to the way LSD or cannabis effect humans.",
    "Cat owners are 17% more likely to have a graduate degree.",
    "Cat owners who are male tend to be luckier in love, as they are perceived as more sensitive.",
    "Cat people are 25% likely to pick George as their favorite Beatle.",
    "Cat people are also 11% more likely to be introverted.",
    "Cats and giraffes are the only known animals to move both of their right feet then both of their left feet when walking.",
    "Cats and humans have nearly identical sections of the brain that control emotion.",
    "Cats are actually able to drink seawater in order to survive.",
    "Cats are actually able to taste scents through the air.",
    "Cats are crepuscular beings, meaning that theyre most active at dawn and dusk.",
    "Cats are extremely sensitive to vibrations. Cats are said to detect earthquake tremors 10 or 15 minutes before humans can.",
    "Cats are often lactose intolerant, so stop givin` them milk!",
    "Cats are really cool.",
    "Cats are the most popular pet in the United States: There are 88 million pet cats and 74 million dogs.",
    "Cats are the only mammals unable to taste sweetness.",
    "Cats can change their meow to manipulate a human. They often imitate a human baby when they need food, for example.",
    "Cats can lick a bone perfectly clean with their rough tongues.",
    "Cats can move their ears 180 degrees.",
    "Cats can`t taste sweetness.",
    "Cats didnt exist in the Americas until Europeans brought them there to exterminate mice.",
    "Cats don’t have sweat glands over their bodies like humans do. Instead, they sweat only through their paws.",
    "Cats have 1,000 times more data storage than an iPad.",
    "Cats have 32 muscles that control the outer ear (humans have only 6). A cat can independently rotate its ears 180 degrees.",
    "Cats have a longer-term memory than dogs, especially when they learn by actually doing rather than simply seeing.",
    "Cats have driven at least 33 species extinct.",
    "Cats have free-floating clavicle bones that attach their shoulders to their forelimbs, which allows them to squeeze through very small spaces.",
    "Cats have inferior daytime sight, but during the night they need seven times less light than humans to see.",
    "Cats have nearly double the number of neurons in their cerebral cortex than dogs do.",
    "Cats have over 20 muscles that control their ears.",
    "Cats have scent glands along their tail, their forehead, lips, chin, and the underside of their front paws.",
    "Cats have the biggest eyes relative to the size of their head of any mammal.",
    "Cats have whiskers on the backs of their front legs.",
    "Cats lick themselves to get your scent off.",
    "Cats like to sleep on things that smell like their owner.",
    "Cats live longer if kept inside.",
    "Cats love laundry baskets because theyre good hiding spots that provide them with peepholes.",
    "Cats make about 100 different sounds. Dogs make only about 10.",
    "Cats make more than 100 different sounds whereas dogs make around 10.",
    "Cats often dream.",
    "Cats only sweat through their foot pads.",
    "Cats perceive humans as large, hairless cats.",
    "Cats really hate the smell of citrus.",
    "Cats sleep 70% of their lives.",
    "Cats spend nearly 1/3 of their waking hours cleaning themselves.",
    "Cats take direct eye contact as a threat.",
    "Cats use their whiskers to detect if they can fit through a space.",
    "Cats were mythic symbols of divinity in ancient Egypt.",
    "Cats with question mark tails are in a playful mood.",
    "Certain cats adore the smell of chlorine.",
    "Eighty-eight percent of cats in the U.S. are spayed or neutered.",
    "Every year, nearly four million cats are eaten in Asia.",
    "Evidence suggests domesticated cats have been around since 3600 B.C., 2,000 years before Egypt`s pharaohs.",
    "Female cats are typically right-pawed while male cats are typically left-pawed.",
    "Female cats can get pregnant from as young as 4 months old.",
    "Hearing is the strongest of cat`s senses: They can hear sounds as high as 64 kHz — compared with humans, who can hear only as high as 20 kHz.",
    "However, a cat called the Turkish Van does not have that insulation problem and LOVES it.",
    "If a cat attacks your ankles, its probably doing so out of boredom.",
    "If a cat blinks slowly at you, it shows that it trusts you and is happy.",
    "If they have ample water, cats can tolerate temperatures up to 133°F.",
    "If you want to adopt a cat, you can visit your local Humane Society or check out petfinder.com.",
    "In contrast to dogs, cats have not undergone major changes during their domestication process.",
    "In the 15th century, Pope Innocent VIII began ordering the killing of cats, pronouncing them demonic.",
    "In the original Italian version of Cinderella, the benevolent fairy godmother figure was a cat.",
    "In tigers and tabbies, the middle of the tongue is covered in backward-pointing spines, used for breaking off and gripping meat.",
    "Isaac Newton is credited with inventing the cat door.",
    "It was illegal to slay cats in ancient Egypt, in large part because they provided the great service of controlling the rat population.",
    "Many Egyptians worshiped the goddess Bast, who had a woman’s body and a cat’s head.",
    "Most cats don`t like water because their coats do not insulate them well enough.",
    "Most cats give birth to a litter of between one and nine kittens. The largest known litter ever produced was 19 kittens, of which 15 survived.",
    "Most cats had short hair until about 100 years ago when it became fashionable to own cats and experiment with breeding.",
    "Most world languages have a similar-sounding word to describe cats meow sound.",
    "Neutered male cats need to consume fewer calories each day.",
    "On average, cats spend 15-20 hours per day sleeping! That means they are only active for 4-8 hours per day, some even less!",
    "One legend claims that cats were created when a lion on Noah`s Ark sneezed and two kittens came out.",
    "One reason that kittens sleep so much is that a growth hormone is released only during sleep.",
    "Only 11.5% of people consider themselves cat-people.",
    "Only 24% of cats who enter animal shelters are adopted.",
    "Original kitty litter was made out of sand but it was replaced by more absorbent clay in 1948.",
    "Owning a cat can reduce the risk of stroke and heart attack by a third.",
    "Polydactyl cats are also referred to as Hemingway-cats because the author was so fond of them.",
    "Similarly, the frequency of a domestic cat`s purr is the same at which muscles and bones repair themselves.",
    "Still, cat people are more open to new experiences than typical dog-people.",
    "The biggest wildcat today is the Siberian Tiger. It can be more than 12 feet long (about the size of a small car) and weigh up to 700 pounds.",
    "The costliest cat ever is named Little Nicky, who cost his owner $50,000. He is a clone of an older cat.",
    "The Egyptian Mau is probably the oldest breed of cat. In fact, the breed is so ancient that its name is the Egyptian word for “cat.”",
    "The Egyptian Mau is the oldest breed of cat.",
    "The Egyptian word for cat is, in fact, mau.",
    "The first cat in space was French. She was named Felicette, or Astrocat. She survived the trip.",
    "The first domesticated cats first appeared at around 3600 BC.",
    "The first-ever cat video was recorded in 1894.",
    "The largest litter of kittens produced 19 kittens.",
    "The mayor of Alaskas Talkeetna district is a cat called Stubbs.",
    "The oldest cat video on YouTube dates back to 1894 (when it was made, not when it was uploaded, duh).",
    "There are 45 Hemingway cats living at the author`s former home in Key West, Fla.",
    "There are cats who have survived falls from over 32 stories (320 meters) onto concrete.",
    "There are more than 500 million domestic cats in the world, with approximately 40 recognized breeds.",
    "There are up to 60 million feral cats in the United States alone.",
    "The smallest wildcat today is the Black-footed cat. The females are less than 20 inches long and can weigh as little as 2.5 lbs.",
    "The technical term for hairball is bezoar.",
    "The world`s largest cat measured 48.5 inches long.",
    "The world`s richest cat is worth $13 million after his human passed away and left her fortune to him.",
    "They also had elaborate memorials that included mummifying the cat and either burying it in a family tomb or pet cemetery.",
    "They are also very soft.",
    "They can also move their ears separately.",
    "This breed is also the fastest pedigreed cat.",
    "Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.",
    "When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.",
    "When a family cat died in ancient Egypt, family members would shave off their eyebrows as they mourned.",
    "When asked if her husband had any hobbies, Mary Todd Lincoln is said to have replied cats.",
    "When cats leave their poop uncovered, it is a sign of aggression to let you know they don`t fear you.",
    "When your cat brings home a dead mouse or bird, it may do so to show you that you suck at hunting.",
    "Wikipedia has a recording of a cat meowing because why not?",
    "Your cat recognizes your voice but just acts too cool to care (probably because they are).",
]
PREFIXES = [
    "Fun fact", "Did you know", "I bet you dont know",  "Here is a neat tidbit",
    "I know a secret", "I bet Karthik 1.0 didnt know",
    ]
  
def fun_fact(handler):
    pfx = random.choice(PREFIXES)
    fact = random.choice(FACTS)
    wav1 = flite(pfx)
    wav2 = flite(fact)
    handler.play_audio([wav1, wav2], pfx + ": " + fact)

class FunFacts:
    """Show a fun fact"""
    def __init__(self, cbhandler):
        self.cbhandler = cbhandler

    def do_fact(self, *args):
        fun_fact(self.cbhandler)

if __name__ == "__main__":
    for fact in FACTS:
        flite(fact)
    for pfx in PREFIXES:
        flite(pfx)
    fun_fact()

